### ISSUE TITLE
Unused code

### ISSUE THREAD

**Issue by githwxi** [August-Alm/ATS-Experiments#1]
By the way, the following code is not needed:

```ats
implement
gcompare_val_val<input>(x, y) = $I.compare(x, y)
```

because 'input' is now assumed to be 'int'. I forgot to delete it :(

**Comment by August-Alm** [comment]
Strangely, I can't get the code to compile without it!

**Comment by githwxi** [comment]
I see. I would feel more comfortable with the following code:

```ats
implement
  gcompare_val_val<input>(x, y) = g0int_compare(x, y)
```

I don't actually understand why $I.compare also works in this context.

**Comment by August-Alm** [comment]
I've changed to [g0int_compare]. I'm closing the issue since I guess it was rather a compiler issue (if indeed an issue at all) than an issue with the code in question. :)
